version: '3'
services:
  api:
    image: hongquangraem/forum-nodejs:202210415.prod.3
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always
    depends_on:
      - mongo
      - redis
    logging:
      driver: 'json-file'
      options:
        max-size: '100M'
        max-file: '3'
  mongo:
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongodo-data/:/data/
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '100M'
        max-file: '3'
  redis:
    image: bitnami/redis:4.0.14
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data/:/data/
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '100M'
        max-file: '3'
